// src/ui/src/lib/components/inspector/InspectorPanel.svelte
<script lang="ts">
  // ---------------------------------------------------------------------------
  // InspectorPanel — 3-mode panel: context list, document view, event detail.
  //
  // Modes:
  //   context_list  — sidebar with document buttons
  //   document      — full detail view with toolbar (raw/rendered, copy, popout)
  //   tool_call / artifact / plan — JSON event detail (auto-synthesised as doc)
  //
  // Resize: drag left edge handle between 260–700 px.
  // CodeMirror 6 for syntax-highlighted code files (ADR-005).
  // @humanspeak/svelte-markdown for rendered markdown.
  // ---------------------------------------------------------------------------

  import { X, ExternalLink, Copy, Check } from '@lucide/svelte';
  import { Button } from '$lib/components/ui/button';
  import { Root as ScrollArea } from '$lib/components/ui/scroll-area';
  import SvelteMarkdown from '@humanspeak/svelte-markdown';
  import { uiAccent } from '$lib/utils/palette';
  import type { InspectorTarget, ContextDocument } from '$lib/data/types';
  import { inspectorState } from '$lib/stores/inspector-state.svelte';
  import CodeBlock from './CodeBlock.svelte';

  let {
    target,
    onclose,
    ondocumentopen,
  }: {
    target: InspectorTarget;
    onclose: () => void;
    ondocumentopen?: (doc: ContextDocument) => void;
  } = $props();

  const copySuccess = uiAccent('copySuccess');

  // ── Language detection ─────────────────────────────────────────────────────

  const EXT_MAP: Record<string, string> = {
    ts: 'typescript',
    tsx: 'tsx',
    js: 'javascript',
    jsx: 'jsx',
    py: 'python',
    rs: 'rust',
    java: 'java',
    kt: 'kotlin',
    go: 'go',
    c: 'c',
    cpp: 'cpp',
    cs: 'csharp',
    rb: 'ruby',
    sh: 'bash',
    bash: 'bash',
    zsh: 'bash',
    yaml: 'yaml',
    yml: 'yaml',
    json: 'json',
    toml: 'toml',
    md: 'markdown',
    mdx: 'markdown',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    less: 'less',
    sql: 'sql',
    graphql: 'graphql',
    gql: 'graphql',
    xml: 'xml',
    svg: 'xml',
    dockerfile: 'docker',
    tf: 'hcl',
    hcl: 'hcl',
    lua: 'lua',
    php: 'php',
    swift: 'swift',
    dart: 'dart',
    r: 'r',
    proto: 'protobuf',
  };

  const CODE_EXTS = new Set([
    'ts',
    'tsx',
    'js',
    'jsx',
    'py',
    'rs',
    'java',
    'go',
    'c',
    'cpp',
    'sh',
    'json',
    'yaml',
    'toml',
    'sql',
    'html',
    'css',
    'rb',
    'kt',
    'swift',
    'dart',
    'php',
  ]);

  function getExt(title: string): string {
    return title.split('.').pop()?.toLowerCase() ?? '';
  }

  function detectLanguage(title: string, content: string): string {
    const ext = getExt(title);
    if (ext && EXT_MAP[ext]) return EXT_MAP[ext];
    const trimmed = content.trim();
    if (trimmed.startsWith('{') || trimmed.startsWith('[')) return 'json';
    if (content.includes('def ') && content.includes(':')) return 'python';
    if (content.includes('fn ') && content.includes('->')) return 'rust';
    if (content.includes('public class') || content.includes('import java.'))
      return 'java';
    if (content.includes('import React') || content.includes('export default'))
      return 'typescript';
    return 'text';
  }

  function isMarkdown(title: string): boolean {
    const ext = getExt(title);
    return ext === 'md' || ext === 'mdx';
  }

  function isCodeFile(doc: ContextDocument): boolean {
    if (doc.type === 'file') return true;
    const ext = getExt(doc.title);
    return CODE_EXTS.has(ext);
  }

  // ── Popout ─────────────────────────────────────────────────────────────────

  function buildPopoutHtml(doc: ContextDocument, isDarkMode: boolean): string {
    const md = isMarkdown(doc.title);
    const fg = isDarkMode ? '#e2e8f0' : '#1e293b';
    const bg = isDarkMode ? '#0f172a' : '#ffffff';
    const preBg = isDarkMode ? '#1e293b' : '#f1f5f9';
    const border = isDarkMode ? '#334155' : '#e2e8f0';
    const quote = isDarkMode ? '#94a3b8' : '#64748b';
    const link = isDarkMode ? '#60a5fa' : '#2563eb';

    if (md) {
      return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>${doc.title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 48rem; margin: 2rem auto; padding: 0 1.5rem;
    color: ${fg}; background: ${bg}; line-height: 1.7; }
  pre { background: ${preBg}; padding: 1rem; border-radius: 0.375rem; overflow-x: auto; }
  code { font-size: 0.875rem; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid ${border}; padding: 0.5rem 0.75rem; text-align: left; }
  blockquote { border-left: 3px solid ${border}; margin-left: 0; padding-left: 1rem; color: ${quote}; }
  img { max-width: 100%; }
  a { color: ${link}; }
  h1,h2,h3,h4,h5,h6 { margin-top: 1.5em; }
</style>
</head><body>
<div id="content"></div>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>
<script>document.getElementById('content').innerHTML = marked.parse(${JSON.stringify(doc.content)});<\/script>
</body></html>`;
    }

    const escaped = doc.content
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>${doc.title}</title>
<style>
  body { font-family: ui-monospace, 'Cascadia Code', 'Fira Code', monospace;
    margin: 2rem; color: ${fg}; background: ${bg}; }
  pre { white-space: pre-wrap; word-wrap: break-word; font-size: 0.8125rem; line-height: 1.6; }
</style>
</head><body><pre>${escaped}</pre></body></html>`;
  }

  function handlePopout(doc: ContextDocument) {
    const isDark = document.documentElement.classList.contains('dark');
    const html = buildPopoutHtml(doc, isDark);
    const dataUri = 'data:text/html;charset=utf-8,' + encodeURIComponent(html);
    const a = document.createElement('a');
    a.href = dataUri;
    a.target = '_blank';
    a.rel = 'noopener noreferrer';
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }

  // ── Copy ───────────────────────────────────────────────────────────────────

  let copied = $state(false);

  async function handleCopy(content: string) {
    try {
      await navigator.clipboard.writeText(content);
      copied = true;
    } catch {
      // Fallback for environments without Clipboard API
      const ta = document.createElement('textarea');
      ta.value = content;
      ta.style.position = 'fixed';
      ta.style.left = '-9999px';
      document.body.appendChild(ta);
      ta.focus();
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      copied = true;
    }
    setTimeout(() => {
      copied = false;
    }, 2000);
  }

  // ── Resize (drag left edge) ────────────────────────────────────────────────

  let resizing = $state(false);
  let resizeStartX = 0;
  let resizeStartWidth = 0;

  function onResizeMouseDown(e: MouseEvent) {
    resizing = true;
    resizeStartX = e.clientX;
    resizeStartWidth = inspectorState.inspectorWidth;
    e.preventDefault();
  }

  $effect(() => {
    if (!resizing) return;

    function onMouseMove(e: MouseEvent) {
      // Dragging left edge: leftward drag increases width
      const delta = resizeStartX - e.clientX;
      inspectorState.setInspectorWidth(resizeStartWidth + delta);
    }

    function onMouseUp() {
      resizing = false;
    }

    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mouseup', onMouseUp);

    return () => {
      window.removeEventListener('mousemove', onMouseMove);
      window.removeEventListener('mouseup', onMouseUp);
    };
  });

  // ── View raw toggle (per-document) ────────────────────────────────────────

  let viewRaw = $state(false);

  // Reset viewRaw when target changes
  $effect(() => {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    target;
    viewRaw = false;
    copied = false;
  });

  // ── Resolved document ─────────────────────────────────────────────────────

  const resolvedDoc = $derived.by((): ContextDocument | null => {
    if (target.type === 'context_list') return null;
    if (target.type === 'document') return target.document ?? null;
    // Synthesise a document from the event for tool_call / artifact / plan
    if (!target.event) return null;
    const typeLabel =
      target.type === 'tool_call'
        ? 'Tool Call'
        : target.type === 'artifact'
          ? 'Artifact'
          : 'Plan Detail';
    return {
      id: target.event.id ?? 'unknown',
      title: typeLabel,
      content: JSON.stringify(target.event, null, 2),
      type: 'note' as const,
      updated_at: target.event.timestamp ?? new Date().toISOString(),
    };
  });
</script>

<!-- ── Resize handle (drag left edge) ──────────────────────────────────────── -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<div
  role="separator"
  aria-orientation="vertical"
  aria-label="Resize inspector panel"
  class="hover:bg-border/60 absolute top-0 left-0 z-10 h-full w-1 cursor-col-resize opacity-0 transition-opacity hover:opacity-100"
  onmousedown={onResizeMouseDown}
></div>

<!-- ── Context list view ────────────────────────────────────────────────────── -->
{#if target.type === 'context_list'}
  <div class="border-border bg-muted/5 flex h-full flex-col border-l">
    <!-- Header -->
    <div
      class="border-border flex shrink-0 items-center justify-between border-b px-3 py-2.5"
    >
      <div class="flex items-center gap-2">
        <span class="text-[0.8125rem] font-semibold tracking-tight">Plans</span>
        <span class="text-muted-foreground text-[0.6875rem]"
          >{target.documents?.length ?? 0}</span
        >
      </div>
      <Button variant="ghost" size="icon" class="h-7 w-7" onclick={onclose}>
        <X class="h-4 w-4" />
      </Button>
    </div>

    <!-- Document list -->
    <ScrollArea class="flex-1" orientation="vertical">
      <div class="space-y-0.5 px-2 py-1">
        {#each target.documents ?? [] as doc (doc.id)}
          <button
            onclick={() => ondocumentopen?.(doc)}
            class="group rounded-terminal hover:bg-accent/50 w-full px-2.5 py-2 text-left transition-colors"
          >
            <div class="flex items-start gap-2">
              <span
                class="text-foreground/80 group-hover:text-foreground flex-1 truncate text-[0.75rem] transition-colors"
              >
                {doc.title}
              </span>
              <span class="text-muted-foreground mt-0.5 shrink-0 text-[0.625rem]">
                {new Date(doc.updated_at).toLocaleDateString([], {
                  month: 'short',
                  day: 'numeric',
                })}
              </span>
            </div>
          </button>
        {/each}
      </div>
    </ScrollArea>
  </div>

  <!-- ── Document / event detail view ─────────────────────────────────────────── -->
{:else if resolvedDoc}
  {@const doc = resolvedDoc}
  {@const isMd = isMarkdown(doc.title)}
  {@const isCode = isCodeFile(doc)}
  {@const lang = detectLanguage(doc.title, doc.content)}
  {@const charCount = doc.content.length.toLocaleString()}
  {@const lineCount = doc.content.split('\n').length}

  <div class="border-border bg-muted/5 flex h-full flex-col overflow-hidden border-l">
    <!-- Header: title + close -->
    <div
      class="border-border flex shrink-0 items-center justify-between border-b px-4 py-3"
    >
      <div class="flex min-w-0 flex-col overflow-hidden">
        <h3 class="mb-1 truncate text-[0.8125rem] leading-none font-semibold">
          {doc.title}
        </h3>
        <span class="text-muted-foreground font-mono text-[0.625rem]">
          {new Date(doc.updated_at).toLocaleString()}
        </span>
      </div>
      <Button
        variant="ghost"
        size="icon"
        class="ml-2 h-7 w-7 shrink-0"
        onclick={onclose}
      >
        <X class="h-4 w-4" />
      </Button>
    </div>

    <!-- Content area -->
    <div class="flex min-h-0 flex-1 flex-col overflow-hidden">
      <div
        class="rounded-terminal border-border mx-4 mt-4 mb-4 flex min-h-0 flex-1 flex-col overflow-hidden border shadow-sm"
      >
        <!-- Content toolbar: filename + actions -->
        <div
          class="border-border bg-muted/40 flex shrink-0 items-center justify-between border-b px-3 py-1.5"
        >
          <span
            class="text-muted-foreground min-w-0 truncate font-mono text-[0.625rem]"
          >
            {doc.title}
          </span>
          <div class="ml-2 flex shrink-0 items-center gap-0.5">
            {#if isMd}
              <Button
                variant="ghost"
                size="icon"
                class="text-muted-foreground hover:text-foreground h-6 w-6"
                onclick={() => {
                  viewRaw = !viewRaw;
                }}
                title={viewRaw ? 'View rendered' : 'View raw'}
              >
                <span class="font-mono text-[0.5625rem] font-bold"
                  >{viewRaw ? 'MD' : '</>'}</span
                >
              </Button>
            {/if}
            <Button
              variant="ghost"
              size="icon"
              class="text-muted-foreground hover:text-foreground h-6 w-6"
              onclick={() => handleCopy(doc.content)}
              title="Copy content"
            >
              {#if copied}
                <Check class="h-3 w-3 {copySuccess.text}" />
              {:else}
                <Copy class="h-3 w-3" />
              {/if}
            </Button>
            <Button
              variant="ghost"
              size="icon"
              class="text-muted-foreground hover:text-foreground h-6 w-6"
              onclick={() => handlePopout(doc)}
              title="Open in new tab"
            >
              <ExternalLink class="h-3 w-3" />
            </Button>
          </div>
        </div>

        <!-- Scrollable content -->
        <ScrollArea class="min-h-0 flex-1" orientation="both">
          {#if isMd && !viewRaw}
            <!-- Rendered markdown -->
            <div
              class="inspector-markdown text-foreground p-4 text-[0.8125rem] leading-relaxed break-words"
            >
              <SvelteMarkdown source={doc.content} />
            </div>
          {:else if isCode && lang !== 'text' && lang !== 'markdown'}
            <!-- Syntax-highlighted code via CodeMirror -->
            <CodeBlock content={doc.content} language={lang} />
          {:else}
            <!-- Plain text / raw -->
            <pre
              class="text-foreground/85 min-h-[12.5rem] p-4 font-mono text-[0.75rem] leading-relaxed break-words whitespace-pre-wrap">{doc.content}</pre>
          {/if}
        </ScrollArea>
      </div>
    </div>

    <!-- Footer metadata -->
    <div class="shrink-0 px-4 pt-0 pb-3">
      <div
        class="text-muted-foreground flex items-center gap-3 font-mono text-[0.625rem]"
      >
        <span>{charCount} chars</span>
        <span class="opacity-40">|</span>
        <span>{lineCount} lines</span>
        <span class="opacity-40">|</span>
        <span>{doc.type === 'file' ? 'Local' : 'External'}</span>
      </div>
    </div>
  </div>
{/if}

<style>
  /* ── Inspector markdown typography ── */
  .inspector-markdown :global(p) {
    margin-bottom: 0.5rem;
  }
  .inspector-markdown :global(p:last-child) {
    margin-bottom: 0;
  }
  .inspector-markdown :global(strong) {
    font-weight: 600;
  }
  .inspector-markdown :global(em) {
    font-style: italic;
  }
  .inspector-markdown :global(h1) {
    font-size: 1rem;
    font-weight: 600;
    margin-top: 1rem;
    margin-bottom: 0.5rem;
  }
  .inspector-markdown :global(h2) {
    font-size: 0.875rem;
    font-weight: 600;
    margin-top: 0.75rem;
    margin-bottom: 0.375rem;
  }
  .inspector-markdown :global(h3) {
    font-size: 0.8125rem;
    font-weight: 600;
    margin-top: 0.625rem;
    margin-bottom: 0.25rem;
  }
  .inspector-markdown :global(h1:first-child),
  .inspector-markdown :global(h2:first-child),
  .inspector-markdown :global(h3:first-child) {
    margin-top: 0;
  }
  .inspector-markdown :global(ul) {
    list-style-type: disc;
    padding-left: 1.25rem;
    margin: 0.375rem 0;
  }
  .inspector-markdown :global(ol) {
    list-style-type: decimal;
    padding-left: 1.25rem;
    margin: 0.375rem 0;
  }
  .inspector-markdown :global(li) {
    margin-bottom: 0.125rem;
  }
  .inspector-markdown :global(blockquote) {
    border-left: 2px solid color-mix(in oklch, var(--foreground) 20%, transparent);
    padding-left: 0.75rem;
    margin: 0.5rem 0;
    color: color-mix(in oklch, var(--foreground) 70%, transparent);
    font-style: italic;
  }
  .inspector-markdown :global(hr) {
    margin: 0.75rem 0;
    border-color: color-mix(in oklch, var(--border) 40%, transparent);
  }
  .inspector-markdown :global(code:not(pre code)) {
    padding: 0.125rem 0.375rem;
    border-radius: var(--radius-terminal, 0.25rem);
    font-size: 0.71875rem;
    font-family: var(--font-mono);
    border: 1px solid color-mix(in oklch, var(--border) 30%, transparent);
    background: color-mix(in oklch, var(--muted) 60%, transparent);
  }
  .inspector-markdown :global(pre) {
    margin: 0.5rem 0;
    border-radius: var(--radius-terminal, 0.25rem);
    border: 1px solid color-mix(in oklch, var(--border) 30%, transparent);
    overflow: hidden;
  }
  .inspector-markdown :global(pre code) {
    display: block;
    padding: 0.75rem 1rem;
    font-size: 0.71875rem;
    font-family: var(--font-mono);
    line-height: 1.6;
    background: color-mix(in oklch, var(--muted) 40%, transparent);
    border: none;
    border-radius: 0;
    overflow-x: auto;
    white-space: pre;
  }
  .inspector-markdown :global(table) {
    width: 100%;
    font-size: 0.71875rem;
    border-collapse: collapse;
    margin: 0.5rem 0;
  }
  .inspector-markdown :global(th) {
    text-align: left;
    padding: 0.25rem 0.625rem;
    font-weight: 600;
    border-bottom: 1px solid color-mix(in oklch, var(--border) 40%, transparent);
  }
  .inspector-markdown :global(td) {
    padding: 0.25rem 0.625rem;
    border-top: 1px solid color-mix(in oklch, var(--border) 30%, transparent);
  }
  .inspector-markdown :global(a) {
    color: var(--accent-0, var(--primary));
    text-decoration: underline;
    text-underline-offset: 2px;
  }
  .inspector-markdown :global(a:hover) {
    opacity: 0.8;
  }
  .inspector-markdown :global(img) {
    max-width: 100%;
  }
</style>

// src/ui/src/app/components/inspector/inspector-panel.tsx
import {
  X,
  ExternalLink,
  RefreshCw,
  Copy,
  Check,
} from "lucide-react";
import { Button } from "../ui/button";
import { ScrollArea } from "../ui/scroll-area";
import { useState } from "react";
import type {
  InspectorTarget,
  ContextDocument,
} from "../../data/types";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import {
  oneDark,
  oneLight,
} from "react-syntax-highlighter/dist/esm/styles/prism";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { uiAccent } from "../../utils/palette";
import { log } from "../../utils/logger";

const copySuccessUi = uiAccent("copySuccess");

interface InspectorPanelProps {
  target: InspectorTarget;
  onClose: () => void;
  isDark?: boolean;
  onOpenDocument?: (doc: ContextDocument) => void;
}

/** Map file extension to Prism language string */
function detectLanguage(
  title: string,
  content: string,
): string {
  const ext = title.split(".").pop()?.toLowerCase();
  const extMap: Record<string, string> = {
    ts: "typescript",
    tsx: "tsx",
    js: "javascript",
    jsx: "jsx",
    py: "python",
    rs: "rust",
    java: "java",
    kt: "kotlin",
    go: "go",
    c: "c",
    cpp: "cpp",
    cs: "csharp",
    rb: "ruby",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    yaml: "yaml",
    yml: "yaml",
    json: "json",
    toml: "toml",
    md: "markdown",
    mdx: "markdown",
    html: "html",
    htm: "html",
    css: "css",
    scss: "scss",
    less: "less",
    sql: "sql",
    graphql: "graphql",
    gql: "graphql",
    xml: "xml",
    svg: "xml",
    dockerfile: "docker",
    tf: "hcl",
    hcl: "hcl",
    lua: "lua",
    php: "php",
    swift: "swift",
    dart: "dart",
    r: "r",
    proto: "protobuf",
  };
  if (ext && extMap[ext]) return extMap[ext];
  if (
    content.trim().startsWith("{") ||
    content.trim().startsWith("[")
  )
    return "json";
  if (content.includes("def ") && content.includes(":"))
    return "python";
  if (content.includes("fn ") && content.includes("->"))
    return "rust";
  if (
    content.includes("public class") ||
    content.includes("import java.")
  )
    return "java";
  if (
    content.includes("import React") ||
    content.includes("export default")
  )
    return "typescript";
  return "text";
}

function isMarkdown(title: string): boolean {
  const ext = title.split(".").pop()?.toLowerCase();
  return ext === "md" || ext === "mdx";
}

function isCodeContent(
  type: ContextDocument["type"],
  title: string,
): boolean {
  if (type === "file") return true;
  const ext = title.split(".").pop()?.toLowerCase();
  return !!(
    ext &&
    [
      "ts", "tsx", "js", "jsx", "py", "rs", "java", "go",
      "c", "cpp", "sh", "json", "yaml", "toml", "sql",
      "html", "css", "rb", "kt", "swift", "dart", "php",
    ].includes(ext)
  );
}

/** Build an HTML page string for popout — rendered markdown or raw source */
function buildPopoutHtml(doc: ContextDocument, isDark: boolean): string {
  const isMd = isMarkdown(doc.title);
  if (isMd) {
    // Render markdown to a styled standalone page
    return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>${doc.title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 48rem; margin: 2rem auto; padding: 0 1.5rem;
    color: ${isDark ? "#e2e8f0" : "#1e293b"};
    background: ${isDark ? "#0f172a" : "#ffffff"}; line-height: 1.7; }
  pre { background: ${isDark ? "#1e293b" : "#f1f5f9"}; padding: 1rem; border-radius: 0.375rem; overflow-x: auto; }
  code { font-size: 0.875rem; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid ${isDark ? "#334155" : "#e2e8f0"}; padding: 0.5rem 0.75rem; text-align: left; }
  blockquote { border-left: 3px solid ${isDark ? "#475569" : "#cbd5e1"}; margin-left: 0; padding-left: 1rem; color: ${isDark ? "#94a3b8" : "#64748b"}; }
  img { max-width: 100%; }
  a { color: ${isDark ? "#60a5fa" : "#2563eb"}; }
  h1,h2,h3,h4,h5,h6 { margin-top: 1.5em; }
</style>
</head><body>
<div id="content"></div>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>
<script>document.getElementById('content').innerHTML = marked.parse(${JSON.stringify(doc.content)});<\/script>
</body></html>`;
  }

  // Non-markdown: raw content in a <pre>
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"/>
<title>${doc.title}</title>
<style>
  body { font-family: ui-monospace, 'Cascadia Code', 'Fira Code', monospace;
    margin: 2rem; color: ${isDark ? "#e2e8f0" : "#1e293b"};
    background: ${isDark ? "#0f172a" : "#ffffff"}; }
  pre { white-space: pre-wrap; word-wrap: break-word; font-size: 0.8125rem; line-height: 1.6; }
</style>
</head><body><pre>${doc.content.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre></body></html>`;
}

// ─── Context List View ─────────────────────────────────────────────────────────
function ContextListView({
  documents,
  onClose,
  onOpenDocument,
}: {
  documents: ContextDocument[];
  onClose: () => void;
  onOpenDocument?: (doc: ContextDocument) => void;
}) {
  return (
    <div className="h-full border-l border-border bg-oxide-sidebar-bg flex flex-col animate-in slide-in-from-right-4 duration-200" role="complementary" aria-label="Plans list">
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2.5 border-b border-border">
        <div className="flex items-center gap-2">
          <span className="text-[0.8125rem] font-semibold tracking-tight">
            Plans
          </span>
          <span className="text-[0.6875rem] text-muted-foreground">
            {documents.length}
          </span>
        </div>
        <Button
          variant="ghost"
          size="icon"
          className="h-7 w-7"
          onClick={onClose}
          aria-label="Close plans panel"
        >
          <X className="h-4 w-4" />
        </Button>
      </div>

      <ScrollArea className="flex-1">
        <div className="px-2 py-1 space-y-0.5" role="list" aria-label="Plan documents">
          {documents.map((doc) => (
            <button
              key={doc.id}
              onClick={() => onOpenDocument?.(doc)}
              role="listitem"
              aria-label={`Open document: ${doc.title}`}
              className="w-full text-left rounded-ui px-2.5 py-2 hover:bg-accent/50 transition-colors group"
            >
              <div className="flex items-start gap-2">
                <span className="flex-1 text-[0.75rem] truncate text-foreground/80 group-hover:text-foreground transition-colors">
                  {doc.title}
                </span>
                <span className="text-[0.625rem] text-muted-foreground shrink-0 mt-0.5">
                  {new Date(doc.updated_at).toLocaleDateString([], {
                    month: "short",
                    day: "numeric",
                  })}
                </span>
              </div>
            </button>
          ))}
        </div>
      </ScrollArea>
    </div>
  );
}

// ─── Document Detail View ──────────────────────────────────────────────────────
function DocumentView({
  document: doc,
  onClose,
  isDark,
}: {
  document: ContextDocument;
  onClose: () => void;
  isDark: boolean;
}) {
  const [copied, setCopied] = useState(false);
  const [viewRaw, setViewRaw] = useState(false);

  const shouldHighlight = isCodeContent(doc.type, doc.title);
  const language = shouldHighlight
    ? detectLanguage(doc.title, doc.content)
    : "text";
  const highlighterStyle = isDark ? oneDark : oneLight;
  const isMd = isMarkdown(doc.title);

  const handleCopy = async () => {
    try {
      if (!navigator.clipboard) throw new Error("Clipboard API not available");
      await navigator.clipboard.writeText(doc.content);
      setCopied(true);
      log.debug('inspector.copy', `Copied ${doc.title} to clipboard`);
    } catch {
      try {
        const textArea = globalThis.document.createElement("textarea");
        textArea.value = doc.content;
        textArea.style.position = "fixed";
        textArea.style.left = "-9999px";
        textArea.style.top = "0";
        globalThis.document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        const successful = globalThis.document.execCommand("copy");
        if (successful) {
          setCopied(true);
          log.debug('inspector.copy', `Copied ${doc.title} via fallback`);
        }
        globalThis.document.body.removeChild(textArea);
      } catch (fallbackErr) {
        log.error('inspector.copy', `Failed to copy ${doc.title}`, fallbackErr);
      }
    }
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePopout = () => {
    try {
      const html = buildPopoutHtml(doc, isDark);
      const dataUri =
        "data:text/html;charset=utf-8," + encodeURIComponent(html);
      const anchor = globalThis.document.createElement("a");
      anchor.href = dataUri;
      anchor.target = "_blank";
      anchor.rel = "noopener noreferrer";
      anchor.style.display = "none";
      globalThis.document.body.appendChild(anchor);
      anchor.click();
      globalThis.document.body.removeChild(anchor);
      log.debug('inspector.popout', `Opened ${doc.title} in new tab`);
    } catch (err) {
      log.error('inspector.popout', `Failed to open ${doc.title} in new tab`, err);
    }
  };

  return (
    <div className="h-full border-l border-border bg-oxide-sidebar-bg flex flex-col animate-in slide-in-from-right-4 duration-200 overflow-hidden">
      {/* Header — title + close only */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-border shrink-0">
        <div className="flex flex-col min-w-0 overflow-hidden">
          <h3 className="text-[0.8125rem] font-semibold truncate leading-none mb-1">
            {doc.title}
          </h3>
          <span className="text-[0.625rem] text-muted-foreground font-mono">
            {new Date(doc.updated_at).toLocaleString()}
          </span>
        </div>
        <Button
          variant="ghost"
          size="icon"
          className="h-7 w-7 shrink-0 ml-2"
          onClick={onClose}
          aria-label="Close document panel"
        >
          <X className="h-4 w-4" />
        </Button>
      </div>

      {/* Content */}
      <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
        <div className="flex-1 min-h-0 overflow-hidden flex flex-col mx-4 mt-4 mb-4 rounded-ui border border-border shadow-sm">
          {/* Content header bar — filename + actions */}
          <div className="flex items-center justify-between px-3 py-1.5 bg-muted/40 border-b border-border shrink-0">
            <span className="text-[0.625rem] font-mono text-muted-foreground truncate min-w-0">
              {doc.title}
            </span>
            <div className="flex items-center gap-0.5 shrink-0 ml-2">
              {isMd && (
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 text-muted-foreground hover:text-foreground"
                  onClick={() => setViewRaw(!viewRaw)}
                  title={viewRaw ? "View rendered" : "View raw"}
                  aria-label={viewRaw ? "View rendered markdown" : "View raw source"}
                >
                  <span className="text-[0.5625rem] font-mono font-bold">
                    {viewRaw ? "MD" : "</>"}
                  </span>
                </Button>
              )}
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6 text-muted-foreground hover:text-foreground"
                onClick={handleCopy}
                title="Copy content"
                aria-label={copied ? "Copied" : "Copy content"}
              >
                {copied ? (
                  <Check className={`h-3 w-3 ${copySuccessUi.text}`} />
                ) : (
                  <Copy className="h-3 w-3" />
                )}
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-6 w-6 text-muted-foreground hover:text-foreground"
                onClick={handlePopout}
                title="Open in new tab"
                aria-label="Open in new tab"
              >
                <ExternalLink className="h-3 w-3" />
              </Button>
            </div>
          </div>

          {/* Scrollable content area */}
          <ScrollArea className="flex-1 min-h-0">
            <div className="max-w-full overflow-x-hidden">
              {isMd && !viewRaw ? (
                /* Rendered markdown */
                <div className="p-4 prose prose-sm dark:prose-invert max-w-none break-words [&_pre]:overflow-x-auto [&_pre]:max-w-full [&_table]:text-[0.75rem] [&_img]:max-w-full">
                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                    {doc.content}
                  </ReactMarkdown>
                </div>
              ) : shouldHighlight && language !== "text" && language !== "markdown" ? (
                /* Syntax highlighted code */
                <SyntaxHighlighter
                  language={language}
                  style={highlighterStyle}
                  customStyle={{
                    margin: 0,
                    padding: "1rem",
                    fontSize: "0.75rem",
                    lineHeight: "1.6",
                    minHeight: "12.5rem",
                    borderRadius: 0,
                    overflowX: "auto",
                  }}
                  showLineNumbers
                  lineNumberStyle={{
                    color: "var(--muted-foreground)",
                    opacity: 0.6,
                    fontSize: "0.6875rem",
                    minWidth: "2.5em",
                    paddingRight: "1em",
                    userSelect: "none" as const,
                  }}
                  wrapLongLines
                >
                  {doc.content}
                </SyntaxHighlighter>
              ) : (
                /* Plain text / raw markdown */
                <pre className="text-[0.75rem] font-mono whitespace-pre-wrap break-words leading-relaxed text-foreground/85 p-4 bg-card min-h-[12.5rem]">
                  {doc.content}
                </pre>
              )}
            </div>
          </ScrollArea>
        </div>
      </div>

      {/* Footer metadata */}
      <div className="px-4 pb-3 pt-0 shrink-0">
        <div className="flex items-center gap-3 text-[0.625rem] text-muted-foreground font-mono">
          <span>{doc.content.length.toLocaleString()} chars</span>
          <span className="opacity-40">|</span>
          <span>{doc.content.split("\n").length} lines</span>
          <span className="opacity-40">|</span>
          <span>{doc.type === "file" ? "Local" : "External"}</span>
        </div>
      </div>
    </div>
  );
}

// ─── Main InspectorPanel ───────────────────────────────────────────────────────
export function InspectorPanel({
  target,
  onClose,
  isDark = true,
  onOpenDocument,
}: InspectorPanelProps) {
  // Context list view
  if (target.type === "context_list") {
    return (
      <ContextListView
        documents={target.documents || []}
        onClose={onClose}
        onOpenDocument={onOpenDocument}
      />
    );
  }

  // Resolve the document for single-doc views
  const document =
    target.type === "document"
      ? target.document
      : ({
          id: target.event?.id || "unknown",
          title:
            target.type === "tool_call"
              ? "Tool Call"
              : target.type === "artifact"
                ? "Artifact"
                : "Plan Detail",
          content: JSON.stringify(target.event, null, 2),
          type: "note" as const,
          updated_at:
            target.event?.timestamp || new Date().toISOString(),
        } as ContextDocument);

  if (!document) return null;

  return (
    <DocumentView
      document={document}
      onClose={onClose}
      isDark={isDark}
    />
  );
}
