// src/ui/src/lib/components/layout/AppShell.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Sidebar from './Sidebar.svelte';
  import TabBar from './TabBar.svelte';
  import StatusBar from './StatusBar.svelte';
  import { appState } from '$lib/stores/app-state.svelte';
  import { tabState } from '$lib/stores/tab-state.svelte';
  import { threadState } from '$lib/stores/thread-state.svelte';
  import { inspectorState } from '$lib/stores/inspector-state.svelte';

  // Slots/children — these are provided by the integration layer (route page)
  interface Props {
    children?: import('svelte').Snippet;
    streamPanel?: import('svelte').Snippet;
    inspectorPanel?: import('svelte').Snippet;
    permissionModal?: import('svelte').Snippet;
  }

  let { children, streamPanel, inspectorPanel, permissionModal }: Props = $props();

  // ── Inspector resize ──────────────────────────────────────────────────────
  let isResizingInspector = false;

  function handleInspectorResizeMouseDown(e: MouseEvent) {
    e.preventDefault();
    isResizingInspector = true;
    const startX = e.clientX;
    const startWidth = inspectorState.inspectorWidth;

    function onMove(ev: MouseEvent) {
      if (!isResizingInspector) return;
      inspectorState.setInspectorWidth(startWidth - (ev.clientX - startX));
    }
    function onUp() {
      isResizingInspector = false;
      document.removeEventListener('mousemove', onMove);
      document.removeEventListener('mouseup', onUp);
      document.body.style.cursor = '';
      document.body.style.userSelect = '';
    }
    document.body.style.cursor = 'col-resize';
    document.body.style.userSelect = 'none';
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', onUp);
  }

  // ── Keyboard shortcuts ────────────────────────────────────────────────────
  function handleKeydown(e: KeyboardEvent) {
    if (e.ctrlKey && e.key === '.') {
      e.preventDefault();
      appState.toggleSidebar();
    }
    if (e.ctrlKey && e.key === 'i') {
      e.preventDefault();
      if (inspectorState.isOpen) inspectorState.closeInspector();
    }
    if (e.key === 'Escape') {
      if (inspectorState.isOpen) inspectorState.closeInspector();
    }
    if (e.ctrlKey && e.key === 'n') {
      e.preventDefault();
      tabState.clearActiveTab();
    }
  }

  onMount(() => {
    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  });

  const hasActiveTab = $derived(
    tabState.activeTabId !== null &&
      threadState.getThread(tabState.activeTabId) !== null,
  );
</script>

<div
  class="bg-background text-foreground flex h-screen w-screen flex-col overflow-hidden"
>
  <!-- Main row: Sidebar | Content -->
  <div class="flex min-h-0 flex-1">
    <!-- Sidebar -->
    <Sidebar />

    <!-- Main content area -->
    <div class="flex min-h-0 min-w-0 flex-1 flex-col">
      <!-- Tab bar -->
      <TabBar />

      <!-- Stream + Inspector row -->
      <div class="flex min-h-0 min-w-0 flex-1">
        <!-- Stream panel -->
        <div class="flex min-h-0 min-w-0 flex-1 flex-col">
          {#if hasActiveTab}
            {@render streamPanel?.()}
          {:else}
            <!-- Empty state — no active tab -->
            <div class="flex flex-1 items-center justify-center">
              <div class="text-center select-none">
                <h2 class="text-foreground/60 mb-1 text-[1rem] font-semibold">
                  VaultSpec
                </h2>
                <p class="text-muted-foreground text-[0.75rem]">
                  Select a task from the sidebar, or create a new one below.
                </p>
              </div>
            </div>
          {/if}
          <!-- Children (e.g. InputBar) always rendered below stream -->
          {@render children?.()}
        </div>

        <!-- Inspector Panel -->
        {#if inspectorState.isOpen}
          <div
            class="relative h-full shrink-0"
            style="width: {inspectorState.inspectorWidth / 16}rem"
          >
            <!-- Resize handle — left edge -->
            <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
            <div
              role="separator"
              aria-label="Resize inspector panel"
              class="hover:bg-primary/30 active:bg-primary/50 absolute top-0 left-0 z-30 h-full w-1 cursor-col-resize transition-colors"
              onmousedown={handleInspectorResizeMouseDown}
            ></div>
            {@render inspectorPanel?.()}
          </div>
        {/if}
      </div>
    </div>
  </div>

  <!-- Status bar -->
  <StatusBar />

  <!-- Permission modal overlay -->
  {@render permissionModal?.()}
</div>

// src/ui/src/app/components/layout/app-shell.tsx
import { useCallback, useEffect, useState, useRef, useMemo } from 'react';
import { useStore } from 'zustand';
import { useShallow } from 'zustand/react/shallow';
import { Sidebar } from './sidebar';
import { StatusBar } from './status-bar';
import { TabBar } from './tab-bar';
import { MessageStream } from '../stream/message-stream';
import { InputBar } from '../stream/input-bar';
import { InspectorPanel } from '../inspector/inspector-panel';
import { useKeyboardNav } from '../../hooks/use-keyboard-nav';
import { log } from '../../utils/logger';
import { NotificationPills } from '../ui/notification-pills';
import { ShaderBackground } from '../ui/shader-background';
import { appStore } from '../../store/app-store';
import { initWsBridge } from '../../bridge/ws-bridge';
import { useThreadsQuery, useRespondToPermission, useCreateThread } from '../../queries';
import { useTeamPresetsQuery, useTeamStatusQuery } from '../../queries/use-team';
import { useThreadStateQuery } from '../../queries/use-thread-state';
import { wsClient } from '../../api/websocket-client';
import type { TeamPreset } from '../../data/types';

export function AppShell() {
  // ── Zustand store selectors ────────────────────────────────────────────
  const {
    activeTabId,
    tabs,
    streamEvents,
    permissionQueue,
    inspectorTarget,
    contextDocuments,
    themeMode,
    openTransient,
    openPinned,
    pinTab,
    closeTab,
    activateTab,
    clearActiveTab,
    toggleSidebar,
    openInspector,
    closeInspector,
    openDocument,
    toggleContextPanel,
  } = useStore(
    appStore,
    useShallow(s => ({
      activeTabId: s.activeTabId,
      tabs: s.tabs,
      streamEvents: s.streamEvents,
      permissionQueue: s.permissionQueue,
      inspectorTarget: s.inspectorTarget,
      contextDocuments: s.contextDocuments,
      themeMode: s.themeMode,
      openTransient: s.openTransient,
      openPinned: s.openPinned,
      pinTab: s.pinTab,
      closeTab: s.closeTab,
      activateTab: s.activateTab,
      clearActiveTab: s.clearActiveTab,
      toggleSidebar: s.toggleSidebar,
      openInspector: s.openInspector,
      closeInspector: s.closeInspector,
      openDocument: s.openDocument,
      toggleContextPanel: s.toggleContextPanel,
    })),
  );

  const connectionState = useStore(appStore, s => s.connectionState);

  // ── TanStack Query hooks ───────────────────────────────────────────────
  const { data: threads = [] } = useThreadsQuery();
  const { data: teamPresets = [] } = useTeamPresetsQuery();
  const respondToPermissionMutation = useRespondToPermission();
  const createThreadMutation = useCreateThread();

  // Snapshot hydration for active tab
  useThreadStateQuery(activeTabId);

  const { data: agents = [] } = useTeamStatusQuery();

  // ── Derived state ──────────────────────────────────────────────────────
  const activeThread = useMemo(() => {
    if (!activeTabId) return null;
    if (!tabs.some(t => t.threadId === activeTabId)) return null;
    return threads.find(t => t.thread_id === activeTabId) || null;
  }, [activeTabId, tabs, threads]);

  const activeEvents = useMemo(
    () => (activeTabId ? streamEvents[activeTabId] || [] : []),
    [activeTabId, streamEvents],
  );

  const isDark = themeMode === 'dark' || (themeMode === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);

  // Per-thread permission requests for the active thread
  const activeThreadPermissions = useMemo(
    () => activeTabId ? permissionQueue.filter(p => p.thread_id === activeTabId) : [],
    [permissionQueue, activeTabId],
  );

  // Set of thread IDs with pending permissions (for sidebar indicators)
  const threadsWithPermissions = useMemo(
    () => new Set(permissionQueue.map(p => p.thread_id)),
    [permissionQueue],
  );

  // ── WS bridge init ─────────────────────────────────────────────────────
  useEffect(() => {
    const cleanup = initWsBridge();
    return cleanup;
  }, []);

  // ── Subscribe WS to active tab ─────────────────────────────────────────
  useEffect(() => {
    if (!activeTabId || connectionState !== 'connected') return;
    wsClient.subscribe([activeTabId]);
  }, [activeTabId, connectionState]);

  const [selectedPreset, setSelectedPreset] = useState<TeamPreset | null>(null);
  const [inspectorWidth, setInspectorWidth] = useState(420);
  const isResizingInspector = useRef(false);
  const sidebarSearchRef = useRef<(() => void) | null>(null);

  // ── Tab navigation helpers for keyboard shortcut hook ──────────────────
  const closeCurrentTab = useCallback(() => {
    if (activeTabId) closeTab(activeTabId);
  }, [activeTabId, closeTab]);

  const nextTab = useCallback(() => {
    if (tabs.length === 0) return;
    const idx = tabs.findIndex(t => t.threadId === activeTabId);
    const nextIdx = (idx + 1) % tabs.length;
    activateTab(tabs[nextIdx].threadId);
  }, [tabs, activeTabId, activateTab]);

  const prevTab = useCallback(() => {
    if (tabs.length === 0) return;
    const idx = tabs.findIndex(t => t.threadId === activeTabId);
    const prevIdx = (idx - 1 + tabs.length) % tabs.length;
    activateTab(tabs[prevIdx].threadId);
  }, [tabs, activeTabId, activateTab]);

  const activateTabByIndex = useCallback((index: number) => {
    if (tabs.length === 0) return;
    if (index === -1) {
      activateTab(tabs[tabs.length - 1].threadId);
    } else if (index < tabs.length) {
      activateTab(tabs[index].threadId);
    }
  }, [tabs, activateTab]);

  const focusSidebarSearch = useCallback(() => {
    sidebarSearchRef.current?.();
  }, []);

  // ── Centralized keyboard shortcuts ────────────────────────────────────
  useKeyboardNav({
    toggleSidebar,
    closeInspector,
    clearActiveTab,
    closeCurrentTab,
    nextTab,
    prevTab,
    activateTabByIndex,
    focusSidebarSearch,
    hasInspector: !!inspectorTarget,
  });

  // ── Boot log ──────────────────────────────────────────────────────────
  useEffect(() => {
    log.info('app.boot', `VaultSpec initialized — ${threads.length} threads, ${agents.length} agents loaded`, undefined, { surface: true, dismissAfter: 3000 });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSend = useCallback(
    (message: string, opts?: {
      preset?: TeamPreset;
      repo?: string;
      branch?: string;
      featureTag?: string;
    }) => {
      if (!activeThread) {
        createThreadMutation.mutate({
          message,
          preset: opts?.preset || selectedPreset || undefined,
          repo: opts?.repo,
          branch: opts?.branch,
          featureTag: opts?.featureTag,
        });
      }
    },
    [activeThread, createThreadMutation, selectedPreset],
  );

  const isEmptyThread = activeThread && activeEvents.length === 0;
  const isNewThread = isEmptyThread || !activeThread;
  const activeTeam = activeThread ? teamPresets.find(p => p.id === activeThread.team_preset) : null;

  const handleToggleContext = useCallback(() => {
    toggleContextPanel(contextDocuments);
  }, [toggleContextPanel, contextDocuments]);

  const isContextOpen = inspectorTarget?.type === 'context_list';
  const hasActiveTab = activeTabId !== null && activeThread !== null;

  // ── Inspector resize handler ───────────────────────────────────────────
  const handleInspectorMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();
      isResizingInspector.current = true;
      const startX = e.clientX;
      const startWidth = inspectorWidth;

      const onMouseMove = (ev: MouseEvent) => {
        if (!isResizingInspector.current) return;
        const newWidth = Math.max(260, Math.min(700, startWidth - (ev.clientX - startX)));
        setInspectorWidth(newWidth);
      };

      const onMouseUp = () => {
        isResizingInspector.current = false;
        document.removeEventListener('mousemove', onMouseMove);
        document.removeEventListener('mouseup', onMouseUp);
        document.body.style.cursor = '';
        document.body.style.userSelect = '';
      };

      document.body.style.cursor = 'col-resize';
      document.body.style.userSelect = 'none';
      document.addEventListener('mousemove', onMouseMove);
      document.addEventListener('mouseup', onMouseUp);
    },
    [inspectorWidth],
  );

  return (
    <div className="h-screen w-screen flex flex-col bg-background text-foreground overflow-hidden">
      <ShaderBackground />
      <div className="flex-1 flex min-h-0">
        {/* Sidebar */}
        <Sidebar
          threads={threads}
          activeTabId={activeTabId}
          openTransient={openTransient}
          openPinned={openPinned}
          clearActiveTab={clearActiveTab}
          agents={agents}
          threadsWithPermissions={threadsWithPermissions}
          onFocusSearchRef={sidebarSearchRef}
        />

        {/* Main Content Area */}
        <main className="flex-1 flex flex-col min-h-0 min-w-0" role="main" aria-label="Message stream">
          {/* Tab Bar */}
          <TabBar
            tabs={tabs}
            activeTabId={activeTabId}
            threads={threads}
            activateTab={activateTab}
            pinTab={pinTab}
            closeTab={closeTab}
          />

          {/* Stream + Inspector row */}
          <div className="flex-1 flex min-h-0 min-w-0">
            {/* Stream Panel */}
            <div className="flex-1 flex flex-col min-h-0 min-w-0">
              {hasActiveTab ? (
                <>
                  <MessageStream
                    events={activeEvents}
                    onInspect={openInspector}
                    emptyState={isEmptyThread || false}
                    teamPreset={activeTeam || undefined}
                    agents={agents}
                    agentState={activeThread.agent_state}
                    onOpenDocument={openDocument}
                    onToggleContext={handleToggleContext}
                    isContextOpen={isContextOpen}
                    contextDocumentCount={contextDocuments.length}
                    isDark={isDark}
                    pendingPermissions={activeThreadPermissions}
                    onRespondPermission={(requestId, optionId) => {
                      respondToPermissionMutation.mutate({ requestId, optionId });
                    }}
                  />
                  <InputBar
                    agentState={activeThread.agent_state}
                    onSend={handleSend}
                    onStop={() => {}}
                    teamPresets={teamPresets}
                    selectedPreset={activeTeam || selectedPreset}
                    onSelectPreset={setSelectedPreset}
                    isNewThread={!!isNewThread}
                    threads={threads}
                    activeThread={activeThread}
                    isDark={isDark}
                  />
                </>
              ) : (
                <>
                  {/* Empty state — no active tab */}
                  <div className="flex-1 flex items-center justify-center" data-focus-section="stream">
                    <div className="text-center select-none">
                      <h2 className="text-[1rem] font-semibold text-foreground/60 mb-1">VaultSpec</h2>
                      <p className="text-[0.75rem] text-muted-foreground">
                        Select a task from the sidebar, or create a new one below.
                      </p>
                    </div>
                  </div>

                  {/* Input bar in create mode */}
                  <InputBar
                    agentState="idle"
                    onSend={handleSend}
                    teamPresets={teamPresets}
                    selectedPreset={selectedPreset}
                    onSelectPreset={setSelectedPreset}
                    isNewThread={true}
                    threads={threads}
                    isDark={isDark}
                  />
                </>
              )}
            </div>

            {/* Inspector Panel */}
            {inspectorTarget && (
              <div
                className="relative shrink-0 h-full"
                style={{ width: `${inspectorWidth / 16}rem` }}
                role="complementary"
                aria-label="Inspector panel"
                data-focus-section="inspector"
              >
                {/* Resize handle — left edge */}
                <div
                  onMouseDown={handleInspectorMouseDown}
                  tabIndex={0}
                  className="absolute top-0 left-0 w-1 h-full cursor-col-resize hover:bg-primary/30 active:bg-primary/50 transition-colors z-30"
                  role="separator"
                  aria-orientation="vertical"
                  aria-label="Resize inspector panel"
                />
                <InspectorPanel
                  target={inspectorTarget}
                  onClose={closeInspector}
                  isDark={isDark}
                  onOpenDocument={openDocument}
                />
              </div>
            )}
          </div>
        </main>
      </div>

      {/* Status Bar */}
      <StatusBar />

      {/* Notification Pills — surfaces logger warnings/errors/info */}
      <NotificationPills />
    </div>
  );
}
