// src/ui/src/lib/components/layout/TabBar.svelte
<script lang="ts">
  import { X, Loader2 } from '@lucide/svelte';
  import { SvelteMap } from 'svelte/reactivity';
  import { tabState } from '$lib/stores/tab-state.svelte';
  import { threadState } from '$lib/stores/thread-state.svelte';
  import { agentStateDot, type AgentDotDescriptor } from './state-indicators';

  interface TabItemData {
    threadId: string;
    label: string;
    isActive: boolean;
    isPinned: boolean;
    dot: AgentDotDescriptor;
  }

  const tabItems = $derived<TabItemData[]>(
    tabState.tabs.map((tab) => {
      const thread = threadState.getThread(tab.threadId);
      return {
        threadId: tab.threadId,
        label: thread?.nickname || thread?.title || tab.threadId,
        isActive: tabState.activeTabId === tab.threadId,
        isPinned: tab.isPinned,
        dot: thread ? agentStateDot(thread.agent_state) : { kind: 'none' },
      };
    }),
  );

  // Per-tab click state for single/double-click detection
  const clickCounts = new SvelteMap<string, number>();
  const clickTimeouts = new SvelteMap<string, ReturnType<typeof setTimeout>>();

  function handleTabClick(threadId: string, button: number) {
    if (button !== 0) return;
    const count = (clickCounts.get(threadId) ?? 0) + 1;
    clickCounts.set(threadId, count);

    if (count === 1) {
      tabState.activateTab(threadId);
      const t = setTimeout(() => {
        clickCounts.set(threadId, 0);
      }, 300);
      clickTimeouts.set(threadId, t);
    } else if (count === 2) {
      const existing = clickTimeouts.get(threadId);
      if (existing) clearTimeout(existing);
      clickCounts.set(threadId, 0);
      tabState.pinTab(threadId);
    }
  }

  function handleMouseDown(threadId: string, button: number, e: MouseEvent) {
    if (button === 1) {
      e.preventDefault();
      tabState.closeTab(threadId);
    }
  }
</script>

{#if tabState.tabs.length > 0}
  <div
    class="border-border bg-oxide-sidebar-bg flex h-9 shrink-0 items-end overflow-x-auto border-b"
  >
    {#each tabItems as item (item.threadId)}
      <div
        role="tab"
        tabindex="0"
        aria-selected={item.isActive}
        onmousedown={(e) => handleMouseDown(item.threadId, e.button, e)}
        onclick={(e) => handleTabClick(item.threadId, e.button)}
        onkeydown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') tabState.activateTab(item.threadId);
        }}
        class="group border-border/40 relative flex h-full max-w-[14rem] shrink-0 cursor-pointer items-center gap-1.5 border-r px-4 font-mono tracking-tight transition-all select-none {item.isActive
          ? 'bg-oxide-terminal-bg text-foreground shadow-[inset_0_2px_0_var(--primary)]'
          : 'bg-oxide-sidebar-bg text-oxide-metadata hover:text-foreground hover:bg-oxide-terminal-bg/50'}"
      >
        <!-- Status dot -->
        {#if item.dot.kind === 'spinner'}
          <span class="flex shrink-0 items-center">
            <Loader2 class="h-3 w-3 animate-spin {item.dot.colorClass}" />
          </span>
        {:else if item.dot.kind === 'dot'}
          <span class="h-2 w-2 shrink-0 rounded-full {item.dot.colorClass}"></span>
        {/if}

        <!-- Label — italic when transient -->
        <span
          class="truncate text-[0.6875rem] font-bold uppercase {item.isPinned
            ? ''
            : 'italic opacity-60'}"
        >
          {item.label}
        </span>

        <!-- Close button -->
        <button
          onclick={(e) => {
            e.stopPropagation();
            tabState.closeTab(item.threadId);
          }}
          class="rounded-control hover:bg-muted ml-1.5 shrink-0 p-0.5 opacity-0 transition-all group-hover:opacity-60 hover:!opacity-100"
        >
          <X class="h-3 w-3" />
        </button>
      </div>
    {/each}
  </div>
{/if}

// src/ui/src/app/components/layout/tab-bar.tsx
import { X } from 'lucide-react';
import { useRef } from 'react';
import { agentStateDot } from './state-indicators';
import type { EditorTab, ThreadSummary } from '../../data/types';

interface TabBarProps {
  tabs: EditorTab[];
  activeTabId: string | null;
  threads: ThreadSummary[];
  activateTab: (threadId: string) => void;
  pinTab: (threadId: string) => void;
  closeTab: (threadId: string) => void;
}

export function TabBar({ tabs, activeTabId, threads, activateTab, pinTab, closeTab }: TabBarProps) {
  if (tabs.length === 0) return null;

  return (
    <div className="flex items-end border-b border-border bg-oxide-sidebar-bg shrink-0 overflow-x-auto h-9" role="tablist" aria-label="Open tasks" data-focus-section="tab-bar">
      {tabs.map((tab) => {
        const thread = threads.find(t => t.thread_id === tab.threadId);
        const isActive = activeTabId === tab.threadId;
        const label = thread?.nickname || thread?.title || tab.threadId;
        const dot = thread ? agentStateDot(thread.agent_state) : null;

        return (
          <TabItem
            key={tab.threadId}
            label={label}
            isActive={isActive}
            isPinned={tab.isPinned}
            dot={dot}
            onActivate={() => activateTab(tab.threadId)}
            onPin={() => pinTab(tab.threadId)}
            onClose={() => closeTab(tab.threadId)}
          />
        );
      })}
    </div>
  );
}

function TabItem({
  label,
  isActive,
  isPinned,
  dot,
  onActivate,
  onPin,
  onClose,
}: {
  label: string;
  isActive: boolean;
  isPinned: boolean;
  dot: React.ReactNode;
  onActivate: () => void;
  onPin: () => void;
  onClose: () => void;
}) {
  const clickTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);
  const clickCount = useRef(0);

  const handleMouseDown = (e: React.MouseEvent) => {
    // Middle-click closes
    if (e.button === 1) {
      e.preventDefault();
      onClose();
    }
  };

  const handleClick = (e: React.MouseEvent) => {
    if (e.button !== 0) return;
    clickCount.current += 1;

    if (clickCount.current === 1) {
      // Activate immediately on first click
      onActivate();
      clickTimeout.current = setTimeout(() => {
        clickCount.current = 0;
      }, 300);
    } else if (clickCount.current === 2) {
      // Double-click: pin
      if (clickTimeout.current) clearTimeout(clickTimeout.current);
      clickCount.current = 0;
      onPin();
    }
  };

  const handleCloseClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    onClose();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onActivate();
      return;
    }
    if (e.key === 'Delete' || (e.key === 'w' && (e.ctrlKey || e.metaKey))) {
      e.preventDefault();
      onClose();
      return;
    }
    // Arrow key navigation between sibling tabs
    const target = e.currentTarget as HTMLElement;
    const container = target.parentElement;
    if (!container) return;
    const tabs = Array.from(container.querySelectorAll<HTMLElement>('[role="tab"]'));
    const idx = tabs.indexOf(target);
    if (idx === -1) return;
    let nextIdx: number | null = null;
    if (e.key === 'ArrowRight') nextIdx = Math.min(idx + 1, tabs.length - 1);
    if (e.key === 'ArrowLeft') nextIdx = Math.max(idx - 1, 0);
    if (e.key === 'Home') nextIdx = 0;
    if (e.key === 'End') nextIdx = tabs.length - 1;
    if (nextIdx !== null) {
      e.preventDefault();
      tabs[nextIdx].focus();
    }
  };

  return (
    <div
      onMouseDown={handleMouseDown}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      tabIndex={0}
      role="tab"
      aria-selected={isActive}
      aria-label={`${label}${isPinned ? '' : ' (transient)'}${isActive ? ', active' : ''}`}
      className={`group relative flex items-center gap-1.5 h-full px-4 cursor-pointer select-none shrink-0 max-w-[14rem] border-r border-border/40 transition-all font-mono tracking-tight ${
        isActive
          ? 'bg-oxide-terminal-bg text-foreground shadow-[inset_0_2px_0_var(--primary)]'
          : 'bg-oxide-sidebar-bg text-oxide-metadata hover:text-foreground hover:bg-oxide-terminal-bg/50'
      }`}
    >
      {/* Status dot */}
      {dot && (
        <span className="shrink-0 flex items-center justify-center [&>svg]:w-3 [&>svg]:h-3 [&>span]:w-2 [&>span]:h-2">
          {dot}
        </span>
      )}

      {/* Label — italic when transient */}
      <span
        className={`text-[0.6875rem] truncate font-bold uppercase ${
          isPinned ? '' : 'italic opacity-60'
        }`}
      >
        {label}
      </span>

      {/* Close button */}
      <button
        onClick={handleCloseClick}
        aria-label={`Close tab: ${label}`}
        className="shrink-0 ml-1.5 p-0.5 rounded-control opacity-60 hover:opacity-100 hover:bg-muted transition-all"
      >
        <X className="w-3 h-3" />
      </button>
    </div>
  );
}
