// src/ui/src/app/components/stream/error-alert.tsx
import { AlertTriangle } from 'lucide-react';
import { useEffect } from 'react';
import type { ErrorStreamEvent } from '../../data/types';
import { log } from '../../utils/logger';

export function ErrorAlert({ event }: { event: ErrorStreamEvent }) {
  // Surface stream errors through the centralized logger
  useEffect(() => {
    log.error('stream.error', event.message, { code: event.code });
  }, [event.message, event.code]);

  return (
    <div className="px-4 py-1.5">
      <div className="relative w-full rounded-ui border border-status-error/30 bg-status-error/5 px-4 py-3 text-[0.8125rem]" role="alert">
        <div className="flex items-start gap-3">
          <AlertTriangle className="h-4 w-4 text-status-error shrink-0 mt-0.5" />
          <div className="flex-1 min-w-0">
            <p className="font-medium text-status-error">Error</p>
            <p className="text-foreground/80 mt-0.5">{event.message}</p>
            {event.code && (
              <span className="text-[0.6875rem] block mt-1 text-muted-foreground/70 font-mono">
                Code: {event.code}
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// src/ui/src/lib/components/stream/ErrorAlert.svelte
<script lang="ts">
  import { AlertTriangle } from '@lucide/svelte';

  let {
    message,
    code = null,
  }: {
    message: string;
    code?: string | null;
  } = $props();
</script>

<div class="px-4 py-1.5">
  <div
    class="rounded-ui border-status-error/30 bg-status-error/5 relative w-full border px-4 py-3 text-[0.8125rem]"
  >
    <div class="flex items-start gap-3">
      <AlertTriangle class="text-status-error mt-0.5 h-4 w-4 shrink-0" />
      <div class="min-w-0 flex-1">
        <p class="text-status-error font-medium">Error</p>
        <p class="text-foreground/80 mt-0.5">{message}</p>
        {#if code}
          <span class="text-muted-foreground/70 mt-1 block font-mono text-[0.6875rem]">
            Code: {code}
          </span>
        {/if}
      </div>
    </div>
  </div>
</div>
